services:
  db:
    image: postgres:17-alpine
    container_name: michael-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: michael-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: michael-web
    env_file:
      .env
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"
    command: ["waitress-serve", "--host=0.0.0.0", "--port=8080", "web.wsgi:application"]

  bot:
    build: .
    container_name: michael-bot
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["python", "-m", "bot.main"]

volumes:
  postgres_data: